{% set name = "swepy" %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0777c2ecf10faa8c238d689ac9083fcb612da8d069ae963cb292c50309e9f7c8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - matplotlib
    - python >=3.6
    - pytest
    - pandas
    - requests
    - tqdm
    - pynco
    - gdal
    - scikit-image
    - affine
    - netcdf4
    - fsspec
    - xarray
    - mapboxgl
    - jenkspy

test:
  requires:
    - pytest
  files:
    - MEASURES/NSIDC-0630.001/2010.01.01/NSIDC-0630-EASE2_N3.125km-F17_SSMIS-2010001-37H-M-SIR-CSU-v1.3.nc
    - MEASURES/NSIDC-0630.001/2010.01.01/NSIDC-0630-EASE2_N6.25km-F17_SSMIS-2010001-19H-M-SIR-CSU-v1.3.nc
    - mock_server.py
  imports:
    - swepy
    - swepy.pipeline
    - swepy.nsidcDownloader
    - swepy.process
    - swepy.analysis


about:
  home: http://github.com/wino6687/swepy
  license: LGPLv3
  license_family: LGPL

  license_file: LICENSE
  summary: 'A python package for obtaining and manipulating Tb files from the MEaSUREs database'

  description: |
    SWEpy is a Python library designed to simplify access to a passive microwave brightness 
    temperature dataset available at the National Snow and Ice Data Center (NSIDC). 
    This dataset contains Northern and Southern hemisphere imagery along with Equatorial 
    imagery, and can be quite useful in analyzing snow water equivalent (SWE) over large spatial 
    extents. SWEpy contains tools to web scrape, geographically subset, and concatenate files into 
    time cubes. There is an automated workflow to scrape long time series while periodically stopping 
    to geographically subset and concatenate files in order to reduce disk impact.

  dev_url: https://github.com/wino6687/SWEpy

extra:
  recipe-maintainers:
    - wino6687
