travis:
  secure:
    BINSTAR_TOKEN: WCiFFBPycjRLpZ7r2zzq4SoXgNK8l/56PHVrTYEdPzlV/aANGXhZTSSJcT70AUZCPNGGq1qHGMxFrbmZ+k9nT4E2WA2mgQJ1N0CgfKgW+IpiK6I5xHPbIlNWJMihO3IzZ4hrW1yaqdBKYBIezi2bNzazrxMQRghiGa12mq/yhNnPVM3ZR3lKbwc9XvFKI9zZtKHEVT1lCGZQUaX/0VBKWiRo1CKf1kCouIrg6KaSG2A6/EXgMxJekuTJXjUkvsyHFL72xxem6XAwUuTHU0jOnUM+J5IZflju4WHpyZWDKZxDLSlbWoZXlMgDi2xgvp+0ZaSepDXQecQ2AoiwYZpBEYxORbA0+xvv/DztD5T9fMiSBAlAGPYZqZ20k/me7cldBq5zdQJ+a+dDtj/tCjRcnXNE71g8Ns3yLUIGD41PD7h+YDKhEYZ6VvgJ5toP5JLQPIMwlw8U4NwZo5OhHKn+E27g24apjJovhGynlU07eWRE0zs3crFEblg3AzzIH9gu2IrtGg05/cRjRwz7ZAz1FkCdH4m8cmgZkBtWNm3dITuQpf/GZaJkHZo78RYqfBM5FNUjQ2zxr4wLGrnZPnPHAymsBAAPN9QAEk+wRE/UmNLD/8ulh/8uPP8IT4JYabl7YjntfcnhQHHzNbfBWOak6QabxwpaYYBMkgJDPtmJkQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
