travis:
  secure:
    BINSTAR_TOKEN: SnzwjbiZ65Eqmldgyvh4oEtc1esp0aunYlBQFHZIOkr6lWsReufKyLsLfXmXutXK2WUVTMov1b6afGo5DU83OH7v0dg4JJLHvj+97k5VB4exRWKxz+4FF2y9L7V0jZoVx4HHDI3xQjudAQiGKigzboHpF0ufJdZRJ0LJL8ulHtlq4NCFD5fm/OG/1ljQrtYzy+FwvzUTuqFizRCEppEUZO44k5nYtUOgpqdvzJzuIcGO+6ao0fNDeADBrinbjKu78LieF9L2GMVUUxFOzylQFXJW9/4zHU1dpaLvOF8G/ARfrMqrg51p2rCWXGFPXsVK05cVN4ey+Q1rVwwZTmAvBjg9qyHOqFwBd6oT5FJFegqm71OFYTQDE/RkGhIq6HMyoUyVvQ0qS9dPdwjXkmnx7ZDq5Ne+tQ1Q2E2RrDJkJRpi3AGJ5IrGayfiF+1nS9eUgXJVb/KiYy9Du/6UUgivUbAb3yT5LP0aXvacSckwbAuGwZKylmHOWxfVK25kx2JkHjp1VgHKTCDn8NYGvH5CwuHAgDM0nNZoqYEHhT3HE1BL5ofFyGGAlOnfuD7h5MMAvCAK85c3LGc1ZykGRurN6I3+dkxu/q+q2m5P5sGT2otIyuSyL8oWEsndMMw/2ymWySeo1CuNOABbkPrj7FujT8euBb/9udJRe+VZmcO+dK4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
